name: petrel_website
version: 1.0.0+1
publish_to: none
description: Petrel（海燕）Flutter热更新框架官网

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # 状态管理
  get: ^4.6.6
  
  # UI组件
  cupertino_icons: ^1.0.2
  tdesign_flutter: ^0.1.7
  
  # 工具库
  url_launcher: ^6.2.4
  google_fonts: ^6.1.0
  flutter_animate: ^4.2.0+1
  
  # Web优化
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_gen_runner: ^5.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/docs/

flutter_gen:
  output: lib/gen/
  line_length: 80
  integrations:
    flutter_svg: false
