name: web_site
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter:
    sdk: flutter
  tdesign_flutter: ^0.1.7
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  flutter_gen: ^5.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
